version: "3.9"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: third-party-api
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: cca-app
    environment:
      - CONTEXTUAL_API_URL=http://api:5000/patient
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      api:
        condition: service_healthy

  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: cca-client
    ports:
      - "8501:8501"
    depends_on:
      app:
        condition: service_healthy
